### ISSUE TITLE
Build stucks

### ISSUE THREAD

**Issue by icywind** [oculus-samples/voicesdk-samples-whisperer#12]
After setting up the project as the README required, I tried to build this demo for Android.  It got stuck on "Calling IPostGenerateGradleAndroidProject callbacks" forever.  How do I get around it?
![Screenshot 2023-04-05 at 5 06 53 PM](https://user-images.githubusercontent.com/1261195/230240310-b07dec79-2b4e-4f43-9912-8e4c0f2b3893.png)

Environment: MacOS 13.1, Unity Editor 2021.3.18f1, JDK/Android/Graddle settings are default set by Unity

**Comment by julieta-ayala** [comment]
Hi icywind, 
Can you try building the project in Unity [2021.3.9f1](https://unity3d.com/unity/whats-new/2021.3.9)? You can install such version within Unity Hub. Let us know if that fixes the issue.

**Comment by icywind** [comment]
I don't think going back to an older version of the Unity SDK can be called a fix. Are you going to stay on 2021.3.9f1 forever? Can you test this on the latest 2021 LFS?
Anyway I will give it a try.

**Comment by julieta-ayala** [comment]
We will test it in 2021.3.18 and let you know if we find any issues.

**Comment by icywind** [comment]
Just FYI, I also tried another environemt:  Win11/Unity2021.3.22f1 (latest) also got the same issue.
BTW, being stuck on this project, I moved on to test the [Unity-TheWorldBeyond](https://github.com/oculus-samples/Unity-TheWorldBeyond) project and it builds smoothly.

**Comment by julieta-ayala** [comment]
Hi icywind, I just successfully built the apk in MacOS 13.2 Unity/Editor 2021.3.18f. Built didn't get stuck in _"Calling IPostGenerateGradleAndroidProject callbacks"_.
