### ISSUE TITLE
Raycasts not being detected

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/voicesdk-samples-whisperer#13]
Managed to succesfully build to device but on initial consent screen the accept and cancel buttons are not detecting raycasts from controllers?

**Comment by rokeyge** [comment]
Which device are you using?

**Comment by owlandfox** [comment]
Quest 2 / Pro

> Which device are you using?

**Comment by rokeyge** [comment]
Interesting, I just tested it on Q2 and Pro and it worked for me. I have updated the readme with more details on how to build (together with updated SDK and Voice SDK). Could you please give it a try?
