### ISSUE TITLE
Getting error running application, saying wit not initialised 

### ISSUE THREAD

**Issue by KUSACON** [oculus-samples/voicesdk-samples-whisperer#14]
StackTrace

You need to configure Wit before running this project!
UnityEngine.Debug:LogError (object)
Whisperer.LogosController:StartApp () (at Assets/Whisperer/Scripts/Logic/LogosController.cs:97)
Whisperer.LogosController:Fade (single) (at Assets/Whisperer/Scripts/Logic/LogosController.cs:76)
Whisperer.Progress:InvokeCallback () (at Assets/Whisperer/Scripts/Utility/TimerUtils.cs:318)
Whisperer.Progress:Update (single) (at Assets/Whisperer/Scripts/Utility/TimerUtils.cs:124)
Whisperer.TimerUtils:Update () (at Assets/Whisperer/Scripts/Utility/TimerUtils.cs:20)

I have followed the Readme file and created an application in wit.ai and correctly copy pasted it's tokens, still getting the error

**Comment by SavioMenifer** [comment]
You have to assign a reference to Wit configuration asset in the script called "App Voice Experience". This script can be found in the "Loader" scene under the "Management" GameObject.

The readme could definitely use a bit more clarity on how to properly assign the Wit config asset.

**Comment by rokeyge** [comment]
Updated the readme as suggested with more details.
