### ISSUE TITLE
Readme shows wrong Unity version

### ISSUE THREAD

**Issue by SavioMenifer** [oculus-samples/voicesdk-samples-whisperer#15]
The readme shows 2021.3.9f1 as the required Unity version for this project, whereas the project actually requires 2021.3.11f1 as defined in [ProjectSettings/ProjectVersion.txt](https://github.com/oculus-samples/voicesdk-samples-whisperer/blob/main/ProjectSettings/ProjectVersion.txt).

**Comment by rokeyge** [comment]
Updated! Thank you for reporting!
