### ISSUE TITLE
Build gets stuck at "Building Gradle project"

### ISSUE THREAD

**Issue by SavioMenifer** [oculus-samples/voicesdk-samples-whisperer#16]
When a build is started when connected to the internet, the process gets stuck at the "Building Gradle project" stage with no error messages in the console. This is presumably because it cannot connect to the repositories in the [gradle template file](https://github.com/oculus-samples/voicesdk-samples-whisperer/blob/main/Assets/Plugins/Android/baseProjectTemplate.gradle) to resolve dependencies.

**Comment by rokeyge** [comment]
Thank you for reporting! I have removed the gradle template file.
